### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by scarbain** [showlab/X-Adapter#2]
This paper seems incredible! Do you plan on releasing the code for it ?

**Comment by Semolce9** [comment]
Thank you for your interests! I am working on code releasing and I hope it can be done in a month. Please stay tuned!

**Comment by scarbain** [comment]
Great, thanks ! 
I'm really interested in this so if you need any help don't hesitate to ping me, I'm willing to write some code or provide some review of it :)

**Comment by CHMimilanlan** [comment]
Waiting for code releasing too.......

**Comment by yxt132** [comment]
Fantastic work! Can't wait for the code release.

**Comment by MushroomFleet** [comment]
Having trained hundreds of Checkpoints and even more Lora's on past version of SD, i'm watching this project with baited breath to see if we can gain a second wind with X-Adaptor to SDXL !!

**Comment by AG-w** [comment]
this plugin seems the only way that can make SDXL useful like SD1.5

if it exist of course

**Comment by ZhangYang-UCAS** [comment]
good work！！！
your project looks very interesting, do you have a date for it's release?

**Comment by zcfrank1st** [comment]
waiting

**Comment by AG-w** [comment]
I'm just hoping this is not a vaporware

**Comment by waomodder** [comment]
soon™
After a month, there are no status or development reports, so it probably won't happen.

**Comment by Semolce9** [comment]
Still need some time ... Sorry for delay :(

**Comment by showerstomp** [comment]
> Still need some time ... Sorry for delay :(

So no updates?

**Comment by thekarmakazi** [comment]
Hello team!  Anxiously awaiting potential code release.  This would be such an immense help to the community.  Please allow to be open source and benefit all the artists and hobbyists with your wonderful research!

**Comment by Gushousekai195** [comment]
I just started using SDXL, and I miss being able to use my 1.5 LoRAs.

No more delays!

**Comment by waomodder** [comment]
There's no way you're getting out. There's no way you can get it out because you wouldn't have made the code from the beginning anyway.
If the code can't be released after three months, it's not going to be released from the start.
The author is just a liar.

**Comment by Semolce9** [comment]
Code released. Please check.
