### ISSUE TITLE
How would control guidance end affect the adapter parameters

### ISSUE THREAD

**Issue by brycegoh** [showlab/X-Adapter#32]
Hello, was wondering how setting a control guidance end would affect the adapter parameters like `adapter_guidance_start`? Is there a `adapter_guidance_end`?

**Comment by Semolce9** [comment]
Hi, `adapter_guidance_start` defines at which timestep adapter begins to work and it will work until the last timestep so there's no `adapter_guidance_end`. You can refer to section 3.3 **Inference Strategy** in our paper for more information.

**Comment by brycegoh** [comment]
Thank you!
