### ISSUE TITLE
Please tell me whether you plan to provide your training images (Laion-high-resolution containing 300k images) ?

### ISSUE THREAD

**Issue by Jamie-Cheung** [showlab/X-Adapter#34]

**Comment by Semolce9** [comment]
Hi, I just randomly sampled 300k images from the original Laion-high-resolution dataset

**Comment by Jamie-Cheung** [comment]
> Hi, I just randomly sampled 300k images from the original Laion-high-resolution dataset

I found that there are four laion datasets, including Laion COCO, Laion-400M, Laion-5B, LAION-AESTHETICS V2 6.5+.
Can you tell me from which dataset you selected 300Kimages?

**Comment by Semolce9** [comment]
> > Hi, I just randomly sampled 300k images from the original Laion-high-resolution dataset
> 
> I found that there are four laion datasets, including Laion COCO, Laion-400M, Laion-5B, LAION-AESTHETICS V2 6.5+. Can you tell me from which dataset you selected 300Kimages?

https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-high-resolution.md this one
