### ISSUE TITLE
 Sorry, how do I use it exactly?

### ISSUE THREAD

**Issue by masterliu2021** [showlab/X-Adapter#7]
I'm very interested in this feature of yours, but as a non-programmer, I'm not sure how to use it
1.Is this designed for web UI or Comfy UI?
2.Where should I download this installation package to, and besides the code, where in the interface can I see and use it?

**Comment by theonetwoone** [comment]
clone X-adapter
Install Anaconda and cd into the cloned folder then follow the install and usage instructions from the readme. X-Adapter doesn't run in web UI or Comfy at least in the current state.

**Comment by katyukuki** [comment]
Hi, is it possible to convert x-adapter model to lroa like lcm lora although it is difficult and tails also increase?
If possible, it might be possible to use webui to make it stronger.

**Comment by Semolce9** [comment]
We are developing ComfyUI and Gradio implementation. Please stay tuned!
